### ISSUE TITLE
Plans to add consul or vault?

### ISSUE THREAD

**Issue by Ramblurr** [travier/fedora-coreos-nomad#1]
This is an amazing little project! I've wanted to play with fedore coreos for awhile... this is a great intro to it.

I hope you don't mind if I ask a few questions?

* Was this just a demo? Or are you actually using this setup somewhere?
* How does nomad + podman driver get updated? It seems the `nomad-binaries.service` unit only copies the binaries out if they don't already exist on the host
* Do you have any plans to add consul or vault?

**Comment by travier** [comment]
> This is an amazing little project! I've wanted to play with fedore coreos for awhile... this is a great intro to it.

Thanks! Great!

> * Was this just a demo? Or are you actually using this setup somewhere?

I am not running that setup but I've confirmed it works.

> * How does nomad + podman driver get updated? It seems the `nomad-binaries.service` unit only copies the binaries out if they don't already exist on the host

Right now you can essentially `rm` the binaries and reboot and you will get the new version. This is the hard part about updates that Nomad does not cover by itself.

> * Do you have any plans to add consul or vault?

Yes, but I did not have the time to do it yet. Help welcomed!

**Comment by travier** [comment]
I've opened the following distinct issues to track the progress on those topics: #3 #4.

Closing this one but feel free to ask further questions if needed.
